### PR TITLE
fix: CheckJWT clones the request

### LINKED ISSUE #62: CheckJWT should use net/http.Request.Clone
CheckJWT makes a shallow copy of the inbound request near the end of the function in order to set a new context.

In the context of reverse proxies, this can cause trouble. See https://github.com/golang/go/issues/20068 and https://github.com/golang/go/issues/23544.

The preferred way to modify the context of an inbound request is net/http.Request.Clone.

### PR DESCRIPTION
**Pull request by jfatta**
fix #62

~I'll keep it as **draft** until tests are working on `v2` branch.~

### CODE REVIEW

**Review by grounded042 — APPROVED** [review]
🎉

File: jwtmiddleware.go [hunk 1]
```diff
@@ -236,7 +236,7 @@ func (m *JWTMiddleware) CheckJWT(next http.Handler) http.Handler {
 
 		// no err means we have a valid token, so set it into the
 		// context and continue onto next
-		*r = *r.Clone(context.WithValue(r.Context(), ContextKey{}, validToken))
+		r = r.Clone(context.WithValue(r.Context(), ContextKey{}, validToken))
```
Comment (grounded042) [inline jwtmiddleware.go]: yup, good catch on this
